fmod RLTOOL-SWITCHES is
  pr TRUTH-VALUE .
  op printStatusOnContinue : -> Bool .
  op printAxiomFailures : -> Bool .
  op skipQuantifierCheck : -> Bool .
endfm

fmod RLTOOL-DEFAULT-CONFIG is
  pr RLTOOL-SWITCHES .
  eq printStatusOnContinue = false .
  eq printAxiomFailures = false .
  eq skipQuantifierCheck = true .
endfm

fmod RLTOOL-DEBUG-CONFIG is
  pr RLTOOL-SWITCHES .
  eq printStatusOnContinue = true .
  eq printAxiomFailures = true .
  eq skipQuantifierCheck = true .
endfm
