#!/usr/bin/env expect

spawn maude [lindex $argv 0];

while 1 {
  expect {
    -re "\nCONTINUE> type \\(continue \\.\\) to continue\[\r\n]+Maude>" {send "(continue .)\r"}
    "\[\r\n]Maude>"                                                     {interact "\n"}
    eof                                                                 {break}
  }
}
