#!/usr/bin/env bash

set -e

branch_name="$1"   && shift
merge_message="$1" && shift
remote="upstream"

if ! git diff --quiet; then
    echo "Must run with a clean worktree!!!" >&2
    exit 1
fi

git fetch --all
git checkout -B 'master' "$remote/master"
git merge --no-ff --no-edit -m "$merge_message ($branch_name)" "$branch_name"
