set include BOOL off .

fmod CHOICE-DATA is
  sorts Nat MSet State Pred .
  subsorts Nat < MSet .
  op zero : -> Nat [ctor] .
  op s    : Nat -> Nat [ctor] .
  op __   : MSet MSet -> MSet [ctor assoc comm] .
  op {_}  : MSet -> State [ctor] .
  op tt   : -> Pred [ctor] .
  op _=C_ : MSet MSet -> Pred [ctor] .  *** MSet containment
  vars U V : MSet . var N : Nat .
  eq U =C U = tt .
  eq U =C U V = tt .
endfm

mod CHOICE is pr CHOICE-DATA .
  vars U V : MSet .
  --- add extra bracket to test invariant creation
  op [_] : MSet -> State .
  rl [choice] : {U V} => {U} .
endm

load ../../rltool.maude

set show stats off .
set show timing off .
set show loop stats off .
set show loop timing off .
set print conceal on .
print conceal mod_is_sorts_._____endm fmod_is_sorts_.____endfm .

(select CHOICE .)
(use tool varsat for validity on CHOICE-DATA .)
(declare-vars (M:MSet) U (N:Nat) .)
(def-term-set ([N]) | true .)
(inv test-invariant-1 to '`[_`] on ({M}) | true .)
(inv test-invariant-2 to '`[_`] on ({N}) | true .)
(start-proof .)
--- these splits will succeed, since they do not change
--- the sharing of any variable
---set break on .
break select split-action .
(split 1 by (M&1:MSet) = (N) .)
(replace 4 by (M&1:MSet) =/= (N':Nat) .)
(split 5 by (N':Nat) = (N':Nat) and (M&1:MSet) = (N':Nat) .)
--- these splits will fail due to to oversharing
(split 2 by (M:MSet) = (N&2:Nat) .)
(replace 3 by (M&2:MSet) =/= (N':Nat) .)
(split 6 by (N':Nat) = (N':Nat) and (M&2:MSet) = (N':Nat) .)
--- TOOD: add some splits that fail due to undersharing
(step .)

--- test command parser against other use tool variants
(use tool varsat for validty on CHOICE-DATA with CHOICE-DATA .)
(use tool varsat for validty on CHOICE-DATA with CHOICE-DATA CHOICE-DATA .)

quit
