load ../../systems/bank-account.maude
load ../../rltool.maude

(select BANK-ACCOUNT-stop .)
(use tool impsimp for validity on BANK-ACCOUNT-DEFINEDOPS with FOFORMSIMPLIFY-IMP-IMPL .)
(use tool varsat  for unsatisfiability on FVP-NAT-PRED .)
(declare-vars (A:Account) U (Msgs:MsgConf) U 
              (N:Nat) U (M:Nat) U (B:Bool) .)
(def-term-set (< bal: N pend: M overdraft: true > # Msgs) | true \/
              ([A,Msgs]) | true .)
(inv no-overdraft to '`[_`,_`] on
    (< bal: N pend: M overdraft: false > # Msgs) |
    (M <= N) = (true) /\ ---((M) = (debts(Msgs)))
    (debts(Msgs) <= M) = (true)
.)
(start-proof .)
(step .)
(continue .)
(continue .)
(continue .)
(continue .)
(continue .)
(continue .)
(step .)
