load ../../systems/choice.maude
load ../../rltool.maude

(select CHOICE .)

(use tool varsat for unsatisfiability on CHOICE-DATA .)
(use tool varsat for validity         on CHOICE-DATA .)

(declare-vars (M:MSet) U (N:Nat) .)

(def-term-set ({N}) | true .)

--- NOTE: this goal overlaps with the termiating state
---       set so we need to do a case analysis to avoid
---       immediately terminating
(add-goal end-with-singleton : ({M}) | true => ({N}) | (N =C M) = (tt) .)

(start-proof .)

--- Do the needed case analysis here
(case 1 on M:MSet by (M1:MSet M2:MSet) U (N':Nat) .)

(step .)
(step .)
