load ../../systems/dumb-comm-protocol.maude
load ../../rltool.maude

(select DUMB-COMM-PROTOCOL .)
(use tool impsimp for validity on DUMB-COMM-PROTOCOL with FOFORMSIMPLIFY-IMPL .)

(declare-vars (NS:NeDataList) U (NR:NeDataList) U (S:DataList) U (R:DataList) U 
              (M:Nat)         U (N:Nat)         U (N':Nat) .)

(def-term-set (< nil , R , N >) | true .)

(add-goal end-loop-with-seqnum : (< NS , NR , M >) | (len(NR)) = (M) => (< nil , NS NR , N >) | (N) = (len(NS NR)) .)

(start-proof .)
(auto .)
(continue .)
(continue .)
(auto .)
(list-goals .)
quit
