load ibos-sop-base.maude

set show advisories off .
set print attribute on .
---set print with parentheses on .

load ../../rltool.maude
(select IBOS-NONFVP-STOP .)

--- Solved:
--- 1. kernelReceivesOPMessage-pa7-cc1b .)

--- rules that handle webapps directly include:
--- [1] kernelReceivesOPMessage-pa6-cc2b
--- [2] kernelReceivesOPMessage-pa7-cc1b
---(select-rls kernelReceivesOPMessage-pa6-cc2b .)
---(select-rls! kernelReceivesOPMessage-pa6-cc2b kernelReceivesOPMessage-pa7-cc1b .)
---(select-rls new-url .)
---(select-rls stop .)
---(select-rls kernelForwardsOPMessage .)

(select-rls kernelReceivesOPMessage-pa7-cc1a .)

(use tool impsimp for validity on IBOS-NONFVP-STOP with FOFORMSIMPLIFY-IMP-IMPL .)
(use tool varsat for unsatisfiability on IBOS-FVP .)
(declare-vars (C:Configuration) U (WPIS:WebappProcInfoSet) U (NPIS:NetworkProcInfoSet) U (MSG:Message) U (PS:PolicySet) U (NNP:Nat*) U (NWA:Nat*) U (U:Label) .)
(def-term-set ([C]) | true .)
--- INV is a generalized multiset equality between:
--- [1] set of fromKernel messages at the beginning of a list in a netproc
--- [2] labels in WebappInfoSet and NetworkProcInfoSet
(inv sop4 to '`[_`] on
({ C
   < webappmgr | nextWAN(NWA) >
   < kernel | weblabels(WPIS), networklabels(NPIS), displayedTopBar(U), handledCurrently(MSG), msgPolicy(PS), nextNetworkProc(NNP) > } ) |
   (p5(C,WPIS,NPIS)) = (tt)                                  /\
   (p4(C,WPIS,NPIS)) = (tt)                                  /\
   (ch-p4(MSG,WPIS,NPIS)) = (tt)                             /\
   --- these are strengthenings of the invariant above that allow the simplification rules to apply more often
   --- they are not strictly needed for correctness --- the invariant above should be enough
   (dupl(C < webappmgr | none > < kernel | none >)) =/= (tt) /\
   (NNP np<= C) =/= (tt)                                     /\
   (NWA wa<= C) =/= (tt)
.)
(start-proof .)
---set break on .
---break select checkVal .
---set print conceal on .
---print conceal fmod_is_sorts_.____endfm mod_is_sorts_._____endm .
(auto .)
---(focus 517,580 .)
(focus 580 .)
---(case 517 on &53:MsgType by (MSG-RETURN-URL) U (&53:NonRetMsg) .)
(case 580 on &54:MsgType by (MSG-RETURN-URL) U (&54:NonRetMsg) .)
(auto .)
