load ../../contrib/systems/bank-account.maude

get variants in BANK-ACCOUNT :
    [ < bal: n + m + x pend: x     overdraft: ff > #               msgs
    , < bal: n + m + x pend: x + m overdraft: ff > # withdraw(m) , msgs
    ] .

get variants in BANK-ACCOUNT :
    [ < bal: n pend: x overdraft: ff > # withdraw(m) , msgs
    , [ m > n , < bal: n       pend: x       overdraft: tt > # msgs
              , < bal: (n - m) pend: (x - m) overdraft: ff > # msgs
      ]
    ] .

get variants in BANK-ACCOUNT :
    [ < bal: n     pend: x overdraft: ff > # msgs
    , < bal: n + m pend: x overdraft: ff > # msgs
    ] .
