

load ../../contrib/systems/imp.maude

mod IMP-TEST is
   protecting IMP-SEMANTICS + IMP-PROGRAMS .

   ops x y z t q r n s : -> Id .
endm

rewrite < x = 3 ; ~> done | x |-> 0 > .

rewrite < sum(n, s) ~> done | n |-> 10 * s |-> 3 > .

rewrite < swap(x, y, t)       ~> done | x |-> 3 * y |-> 5 * t |-> 0 > .
rewrite < swap-in-place(x, y) ~> done | x |-> 3 * y |-> 5 > .

rewrite < swap-sort(x ; y ; z)         ~> done | x |-> 3 * y |-> 4 * z |-> 5 > .
rewrite < swap-sort(x ; z ; y)         ~> done | x |-> 3 * y |-> 4 * z |-> 5 > .
rewrite < swap-sort(y ; z ; x)         ~> done | x |-> 3 * y |-> 4 * z |-> 5 > .
rewrite < swap-sort(y ; z ; q ; x ; r) ~> done | x |-> 3 * y |-> 4 * z |-> 5 * r |-> 7 * q |-> 3 > .

mod THREADED-IMP-TEST is
   protecting THREADED-IMP-SEMANTICS + IMP-PROGRAMS .

   ops x y z t q r n s : -> Id .
endm

rewrite { < swap(x, y, s) ~> done >
          < done | x |-> 3 * y |-> 4 * z |-> 5 * s |-> 0 * t |-> 0 >
        } .

search { < swap(x, y, s) ~> done >
         < swap(y, z, t) ~> done | x |-> 3 * y |-> 4 * z |-> 5 * s |-> 0 * t |-> 0 >
       }
   =>! TP:ThreadPool .
