#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < psising-maudel.maude -no-banner -no-advise \
  > psising-maudel.out 2>&1

diff psising-maudel.expected psising-maudel.out > /dev/null 2>&1
