load ../../contrib/systems/thermostat.maude

mod THERMOSTAT-COMFORTABLE is
    extending THERMOSTAT .

    vars TIME TMP TMP' : Nat .
    var IM : InMode . var MD : DelayMode . var MODE : Mode .

    --- thermostat control parameters
    eq min   = 10 + 8      .
    eq max   = 10 + 10 + 6 .
    eq bound = 3           .

    --- air conditioning warm-up/cool-down times
    eq time-until(on)  = 4 .
    eq time-until(off) = 2 .

    --- temperature deltas in each state
    eq heat-rate(on,         TMP)             = TMP + 2 [variant] .
    eq heat-rate(off,        TMP + 1 + 1 + 1) = TMP     [variant] .
    eq heat-rate(delay(on),  TMP + 1)         = TMP     [variant] .
    eq heat-rate(delay(off), TMP + 1)         = TMP     [variant] .
endm

get variants heat-rate(MODE, TMP) .

search { 0 , 10 + 10 , off } =>* C:Conf .
