#!/bin/sh

MAUDE_LIB=$srcdir/../../../src/Main
export MAUDE_LIB

../../../../src/Main/maude \
  < $srcdir/bank-account.maude -no-banner -no-advise \
  > bank-account.out 2>&1

diff $srcdir/bank-account.expected bank-account.out > /dev/null 2>&1
