load ../../../../contrib/systems/dijkstra.maude
load ../../../../contrib/tools/lmc/symbolic-interface.maude

(mod DIJKSTRA-MUTEX-SATISFACTION is
  pr SYMBOLIC-CHECKER .
  pr DIJKSTRA-MUTEX .

  subsort Conf < State .

  ops ex? : -> Prop .

  vars F F' : Flag . var S : Status .
  var CPS : CProcSet .     var PS : ProcSet .
  var CNS : CNCrtProcSet . var NS : NCrtProcSet .
  var CIS : CInitProcSet .

  eq < CNS >                        |= ex? = true  [variant] .
  eq < {F,crit,-} CNS >             |= ex? = true  [variant] .
  eq < {F,crit,!} NS >              |= ex? = true  [variant] .
  eq < {F,crit,-} {F',crit,-} CPS > |= ex? = false [variant] .
  eq < {F,crit,!} {F',crit,-} PS >  |= ex? = false [variant] .
  eq < {F,crit,-} {F',crit,!} PS >  |= ex? = false [variant] .
endm)

(mod DIJKSTRA-MUTEX-SATISFACTION-WIDENING is
  pr DIJKSTRA-MUTEX-SATISFACTION .

  var F : Flag .  var CIS : CInitProcSet .  var CPS : CProcSet .

--- bisimilar equational abstraction
  eq < {F,l2,-} {F,l2,-} CPS > = < {F,l2,-} CPS > [variant] .

endm)

set verbose on .

---   true (complete with depth 16)
(lfmc < CIS > |= [] ex?  .)
