#!/bin/sh

MAUDE_LIB=$srcdir/../../../src/Main
export MAUDE_LIB

../../../src/Main/maude \
  < mconstruction.maude -no-banner -no-advise \
  > mconstruction.out 2>&1

diff mconstruction.expected mconstruction.out > /dev/null 2>&1
