#!/bin/sh

MAUDE_LIB=$srcdir/../../../src/Main
export MAUDE_LIB

../../../src/Main/maude \
  < sort-ops.maude -no-banner -no-advise \
  > sort-ops.out 2>&1

diff sort-ops.expected sort-ops.out > /dev/null 2>&1
