set show timing off .

load ../../../contrib/tools/meta/structured-names.maude

fmod TEST-STRUCTURED-NAME is
   protecting STRUCTURED-NAME .

   ops X Y Z F : -> Sort .
   -----------------------
    eq X = var<Sort>('X) .
    eq Y = var<Sort>('Y) .
    eq Z = var<Sort>('Z) .
    eq F = var<Sort>('F) .

   ops x y z f : -> Sort .
   -----------------------
    eq x = 'x .
    eq y = 'y .
    eq z = 'z .
    eq f = 'f .
endfm

--- Module STRUCTURED-NAMES
--- -----------------------

reduce x ==> y .
reduce x ==> y ==> z .
reduce (x ==> y) ==> z == x ==> y ==> z .
reduce x ==> (y ==> z) == x ==> y ==> z .

reduce resolveNames(x ==> y) .
reduce resolveNames(x ==> y ==> z) .
reduce resolveNames((x ==> y) ==> z) == resolveNames(x ==> y ==> z) .
reduce resolveNames(x ==> (y ==> z)) == resolveNames(x ==> y ==> z) .

reduce prime(X) .
reduce prime(3, X) .
reduce prime(3, F{X}) .
reduce prime(3, 'F{X}) .

reduce prime(X, X) .
reduce prime(X, Y) .
reduce prime(X, F{X}) .
reduce prime(X, 'F{X}) .
reduce prime(2, X, F{X}) .

reduce prime(Y, F{X}) .
reduce prime(X, F{F{X}}) .
reduce prime(X, F{(F{X}) (F{X})}) .
reduce prime(F, F{(F{X}) (F{X})}) .
