#!/bin/sh

MAUDE_LIB=$srcdir/../../../src/Main
export MAUDE_LIB

../../../src/Main/maude \
  < bintree.maude -no-banner -no-advise \
  > bintree.out 2>&1

diff bintree.expected bintree.out > /dev/null 2>&1
