#!/bin/sh

MAUDE_LIB=$srcdir/../../../src/Main
export MAUDE_LIB

../../../src/Main/maude \
  < ordlist.maude -no-banner -no-advise \
  > ordlist.out 2>&1

diff ordlist.expected ordlist.out > /dev/null 2>&1
