#!/bin/sh

MAUDE_LIB=$srcdir/../../../src/Main
export MAUDE_LIB

../../../src/Main/maude \
  < searchtree.maude -no-banner -no-advise \
  > searchtree.out 2>&1

diff searchtree.expected searchtree.out > /dev/null 2>&1
